version : '2'
services:
    mariadb:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password1
        volumes:
            - "./PatientInfo/src/main/resources/PatientInfo.sql:/docker-entrypoint-initdb.d/1.sql"
            - patient_info_data:/var/lib/mysql

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: jessuisgroot
            MONGO_INITDB_ROOT_DATABASE: demo
        volumes:
            - note_data:/data/db

    note:
        depends_on:
            - mongo
        image: note
        restart: always
        ports:
            - "8082:8082"
        environment:
            SPRING_DATA_MONGODB_HOST: mongo
            SPRING_DATA_MONGODB_PORT: 27017
            SPRING_DATA_MONGODB_USERNAME: root
            SPRING_DATA_MONGODB_PASSWORD: jessuisgroot

    patientinfo:
        depends_on:
            - mariadb
        image: patientinfo
        restart: always
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/demo
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: password1

    assessment:
        depends_on:
            - patientinfo
            - note
        image: assessment
        restart: always
        ports:
            - "8080:8080"
        environment:
            URL_PATIENTINFO: http://patientinfo:8081
            URL_NOTE: http://note:8082

    mediscreenui:
        depends_on:
            - patientinfo
            - note
            - assessment
        image: mediscreenui
        ports:
            - "8083:8083"
        restart: always
        environment:
            URL_ASSESSMENT: http://assessment:8080
            URL_PATIENTINFO: http://patientinfo:8081
            URL_NOTE: http://note:8082
volumes:
    patient_info_data:
    note_data:
