version : '2'
services:
    mariadb:
        image: mariadb
        restart: always

    patientinfo:
        depends_on:
            - mariadb
        image: patientinfo
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/demo
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: password1

    clientui:
        depends_on:
            - patientinfo
        image: mediscreenui
        ports:
            - "8080:8080"
        restart: always
        environment:
            URL_PATIENTINFO: http://patientinfo:8081
